// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createSupabaseClient = () => {
  // Check if we're in a browser environment
  const isBrowser = typeof window !== 'undefined';
  
  // Validate required environment variables
  if (!SUPABASE_URL) {
    throw new Error('Missing SUPABASE_URL environment variable');
  }
  
  if (!SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Missing SUPABASE_ANON_KEY environment variable');
  }
  
  return createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isBrowser ? localStorage : undefined,
      persistSession: isBrowser,
      autoRefreshToken: isBrowser,
    }
  });
};

export const supabase = createSupabaseClient();